### ISSUE TITLE
Package proposal: resource-hacker.vm

### ISSUE THREAD

**Issue by mr-tz** [mandiant/VM-Packages#433] opened 2023-06-14 09:23 UTC
### Package Name

resource-hacker

### Tool Name

Resource Hacker

### Package type

OTHER/UNKNOWN

### Tool's version number

5.1.7.

### Category

PE

### Tool's authors

Angus Johnson

### Tool's description

Resource editor for 32bit and 64bit Windows applications.

### Download URL

http://www.angusj.com/resourcehacker/reshacker_setup.exe

### Download SHA256 Hash

080e97f7c198aeeac2a172f055c09d8da365b59b58bf6a71bde4486d9992ff66

### Why is this tool a good addition?

Good to browser PE resources.

Note: there's also a ZIP download we may want to use instead

**Comment by Ana06** [comment] 2023-06-14 18:45
Is this a duplicate of https://github.com/mandiant/VM-Packages/issues/161? Should we close https://github.com/mandiant/VM-Packages/issues/161 and add some of the context from there here (as it has a long conversation)? 🤔

**Comment by Ana06** [comment] 2023-10-06 11:43
This package already exist (created by Commando-VM): https://github.com/mandiant/VM-Packages/issues/567 We should add it to flare-vm default configuration

**Closed by Ana06** 2023-10-06 11:43 UTC
Labels: :new: package, :cyclone: FLARE-VM
