### ISSUE TITLE
Hashcat VM

### ISSUE THREAD

**Issue by godylockz** [mandiant/VM-Packages#653] opened 2023-08-30 03:42 UTC
### What's the problem?

[hashcat.vm] vm.common.psm1 [+] ERROR : [ERR] Non-Intel processor detected.

Hashcat should run regardless on the processor / environment.

### Steps to Reproduce

1. Install commando vm 
2. choco install hashcat.vm

### Environment

Windows 10

### Detected by test suite

No

**Comment by Ana06** [comment] 2023-09-27 12:10
@Menn1s do you have some input on this check?

**Comment by day1player** [comment] 2023-10-10 15:29
I'm pretty sure hashcat requires an intel CPU but we can do some testing to double check.. @Menn1s or @nos3curity could one of you test this out?

**Comment by day1player** [comment] 2023-10-10 15:34
Ok looking at the site this is what I found:
<img width="457" alt="image" src="https://github.com/mandiant/VM-Packages/assets/37482972/b783f655-1780-4879-853f-e8e5bed5aac8">

Maybe we need to check if there is an OpenCL runtime instead of the processor? Will have to look into that.

**Comment by day1player** [comment] 2023-11-10 16:20
@MalwareMechanic I havent been able to look into this as all of my CPUs are intel but looking at the documentation it says "everything that comes with an OpenCL runtime"

**Comment by Ana06** [comment] 2024-01-12 16:56
@day1player can the check be then updated to fix the package in our test suite?

**Comment by day1player** [comment] 2024-01-16 19:58
I think this one we will have to look into on how to detect the OpenCL runtime

**Comment by Ana06** [comment] 2024-07-17 14:39
closing as I think it was fixed in #892. Please let me know if the issue is not fixed.

**Closed by Ana06** 2024-07-17 14:39 UTC
Labels: :bug: bug, :cyclone: COMMANDO-VM
