### ISSUE TITLE
The installation complete dialog will hang the installation script from exiting in powershell blocking unattended installation.

### ISSUE THREAD

**Issue by RexChenjq** [mandiant/VM-Packages#955] opened 2024-03-21 07:37 UTC
### What's the problem?

I have been trying to install flare-vm automatically but this dialog is causing an issue. Unlike other output using `Write-Host`, this `$form.ShowDialog()` is expecting a user to click the button before the powershell script can exit successfully.

This is painful. Please fix this

### Steps to Reproduce

Any successful installation will end up with the final dialog. -noGui argument is not honoured here.

### Environment

AWS EC2
10.0.20348
5.1.20348.2227
2.2.2
3.0.3

### Detected by test suite

No

**Comment by Ana06** [comment] 2024-03-22 15:55
Duplicate of https://github.com/mandiant/VM-Packages/issues/837

**Closed by Ana06** 2024-03-22 15:55 UTC
Labels: :bug: bug
