### ISSUE TITLE
flarevm.installer.vm not installed. The package was not found with the source(s) listed.

### ISSUE THREAD

**Issue by mexavierace12** [mandiant/VM-Packages#237] opened 2023-02-12 03:30 UTC
### What's the problem?

I don't quite understand how to fix this issue. I tried to download few Windows 10 compatible to setup Flare VM but I'm still getting the same error.

### Steps to Reproduce

...

### Environment

Installing the following packages:
flarevm.installer.vm;Lab\Desktop;.;https://www.myget.org/F/vm-packages/api/v2;https://myget.org/F/vm-packages/api/v2;https://chocolatey.org/api/v2
By installing, you accept licenses for the packages.
flarevm.installer.vm not installed. The package was not found with the source(s) listed.
 Source(s): 'C:\ProgramData\boxstarter\BuildPackages;C:\Users\Malware'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
Lab\Desktop not installed. The package was not found with the source(s) listed.
 Source(s): 'C:\ProgramData\boxstarter\BuildPackages;C:\Users\Malware'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
. not installed. The package was not found with the source(s) listed.
 Source(s): 'C:\ProgramData\boxstarter\BuildPackages;C:\Users\Malware'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
The given path's format is not supported.

### Detected by test suite

I don't know

**Comment by mr-tz** [comment] 2023-02-15 11:07
Hm, can you share your steps to reproduce this, please?

**Comment by mexavierace12** [comment] 2023-02-17 13:47
I have downloaded Win 10 1809 x64 and have in setup in my Vmware.

Then I followed the steps from here.

1. Disable Windows Updates
2. Disable Tamper Protection and any Anti-Malware solution
3. Disabling Tamper Protection
4. Disabling Windows Defender
5. Take a VM snapshot
6. Open a PowerShell prompt as administrator
7. Downloaded the installation script 
(New-Object net.webclient).DownloadFile('https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1',"$([Environment]::GetFolderPath("Desktop"))\install.ps1")
9. Unblock-File .\install.ps1

10. Set-ExecutionPolicy Unrestricted
11. Then I execute the script.
12. .\install.ps1

**Comment by MalwareMechanic** [comment] 2023-02-17 14:21
At the moment there's not a lot of info to help triage this, but from what I can see your Chocolatey sources are not set correctly. From the `Environment` snippet above it appears your sources are set to: 

```
Source(s): 'C:\ProgramData\boxstarter\BuildPackages;C:\Users\Malware'
```

If your sources aren't set correctly then BoxStarter & Chocolatey won't be able to find the correct packages to install -- leading to failure.

Try running the following from an admin PowerShell prompt to set the sources explicitly:

```
Import-Module Boxstarter.Chocolatey
$desktopPath = [Environment]::GetFolderPath("Desktop")
Set-BoxstarterConfig -NugetSources "$desktopPath;.;https://www.myget.org/F/vm-packages/api/v2;https://myget.org/F/vm-packages/api/v2;https://chocolatey.org/api/v2"
choco sources add -n="vm-packages" -s "$desktopPath;.;https://www.myget.org/F/vm-packages/api/v2;https://myget.org/F/vm-packages/api/v2" --priority 1
```

After that try running the script again.

Also concerning, is that it says:

```
Installing the following packages:
flarevm.installer.vm;Lab\Desktop;.;https://www.myget.org/F/vm-packages/api/v2;https://myget.org/F/vm-packages/api/v2;https://chocolatey.org/api/v2
```

and treats this as a semicolon delimited list of packages to install as evident by:

```
Lab\Desktop not installed. 
...
. not installed.
```

This very odd behavior since the installer script specifies `"flarevm.installer.vm"` to be installed (see: https://github.com/mandiant/flare-vm/blob/16fb2c68adc760ea88f176001ed65f758340a6ac/install.ps1#L905). So I'm not sure what is happening there.

Please let us know if any of this helped!

**Comment by Ana06** [comment] 2023-03-17 13:37
@mexavierace12 did the guidance in the last comment fixed your issue?

**Comment by Ana06** [comment] 2024-07-17 14:21
Closing as the issue appears to be fixed.

**Closed by Ana06** 2024-07-17 14:21 UTC
Labels: :bug: bug
