### ISSUE TITLE
Unable to install boxstarter packages through chocolatey 2.0.0

### ISSUE THREAD

**Issue by Rahulvarma-13** [mandiant/VM-Packages#409] opened 2023-06-03 00:37 UTC
### What's the problem?

After running Unblock-File .\install.ps1 command and Set-ExecutionPolicy Unrestricted command, I ran the script using this command for the flare installation:
.\install.ps1 -customConfig https://raw.githubusercontent.com/HuskyHacks/PMAT-labs/main/config.xml

Once the password for VM is entered, the chocolatey was installed and when the boxstarter packages are installing, the flare installation was stopped and I got the following error:
Invoke-Expression: The term 'cinst' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Checked the Chocolatey version and it was 2.0.0   Downgraded the Chocolatey version to 1.4.0 and ran the script again and now the flare installation was successful without any errors.

### Steps to Reproduce

1. In PowerShell Admin prompt, run: (New-Object net.webclient).DownloadFile('https://raw.githubusercontent.com/mandiant/flare-vm/main/install.ps1',"$([Environment]::GetFolderPath("Desktop"))\install.ps1")

2. Change directories to the Desktop

3. Run: Unblock-File .\install.ps1

4. Run: Set-ExecutionPolicy Unrestricted

5. Run: .\install.ps1 -customConfig https://raw.githubusercontent.com/HuskyHacks/PMAT-labs/main/config.xml

6. Enter VM password and click Y to continue the installation process.

### Environment

HostOS : Windows 11 Home
Virtualization software : Virtualbox 7.0

Version                 : 10.0.19045
BuildNumber             : 19045
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
Caption                 : Microsoft Windows 10 Enterprise Evaluation

VM OS HDD Space / Usage
-----

DeviceID DriveType ProviderName VolumeName     Size        FreeSpace
-------- --------- ------------ ----------     ----        ---------
C:       3                                     85286490112 50864492544
D:       5                      VBox_GAs_7.0.8 53485568    0

VM PowerShell Version
-----
5.1.19041.1682

Chocolatey version was now changed to 1.4.0 as i downgraded it to make it work through the installation process. Previously it was 2.0.0

VM Boxstarter Version
-----

Boxstarter|3.0.0
Boxstarter.Bootstrapper|3.0.0
Boxstarter.Chocolatey|3.0.0
Boxstarter.Common|3.0.0
Boxstarter.HyperV|3.0.0
Boxstarter.WinConfig|3.0.0

### Detected by test suite

Yes

**Comment by moatazabdullah** [comment] 2023-06-03 18:35
I encountered the same issue.
Try "choco install Boxstarter" and then run the install.ps1 script.

**Comment by Ana06** [comment] 2023-06-05 09:57
This is caused by Boxstarter not being compatible with Chocolatey 2 (released few days ago) as it uses the deprecated (now removed) `cinst`. You can run `$env:chocolateyVersion = '1.4.0'` before installing flare-vm till https://github.com/chocolatey/boxstarter/pull/533 fix is merged and released.

**Closed** 2023-06-07 14:21 UTC
Labels: :bug: bug
