### ISSUE TITLE
Installation Error for event-log-explorer.vm and fiddleclassic.vm

### ISSUE THREAD

**Issue by cdlinh** [mandiant/VM-Packages#1102] opened 2024-07-08 13:42 UTC
### What's the problem?

I encountered an issue while attempting to install packages using Flare VM. The installation process failed for the packages event-log-explorer.vm and fiddleclassic.vm.

For event-log-explorer.vm, the error indicates a checksum mismatch. The actual checksum does not match the expected value. For fiddleclassic.vm, the error states that it is unable to resolve dependencies.

Error Details:

event-log-explorer.vm:

Error: Hashes do not match. Actual value was 8DC29D4A6208F4214DAC9C9BCE2A6B6979805EBFD57DCCB202717A14F8CC894.
Expected checksum: 843b4a2d639a87f2d301b151fbf07f70282c8b4e07a5642a206d6d6ab63dc3 for checksum type sha256.
Install was NOT successful.
fiddleclassic.vm:

Error: Unable to resolve dependencies. Installation was NOT successful.
Please find the attached log files for further investigation: C:\ProgramData\chocolatey\logs\chocolatey.log.

### Steps to Reproduce

Run choco install event-log-explorer.vm in PowerShell.
Observe the checksum mismatch error.
Run choco install fiddleclassic.vm in PowerShell.
Observe the dependency resolution error.

### Environment

Virtualization software: Vitual Box
![Capture](https://github.com/mandiant/VM-Packages/assets/130452143/cc9777ca-7def-49eb-8a1b-9d48509f02a3)

### Additional Information

1.C:\ProgramData\_VM\log.txt
[log.txt](https://github.com/user-attachments/files/16129207/log.txt)

2.The log files: C:\ProgramData\chocolatey\logs\chocolatey.log.
[choco.summary.log](https://github.com/user-attachments/files/16129178/choco.summary.log)
[chocolatey.1.log](https://github.com/user-attachments/files/16129179/chocolatey.1.log)
[chocolatey.2.log](https://github.com/user-attachments/files/16129180/chocolatey.2.log)
[chocolatey.3.log](https://github.com/user-attachments/files/16129181/chocolatey.3.log)
[chocolatey.4.log](https://github.com/user-attachments/files/16129183/chocolatey.4.log)
[chocolatey.log](https://github.com/user-attachments/files/16129185/chocolatey.log)

### Detected by test suite

No

**Comment by Ana06** [comment] 2024-07-08 14:20
Duplicate of https://github.com/mandiant/VM-Packages/issues/1103

**Closed by Ana06** 2024-07-08 14:20 UTC
Labels: :bug: bug
